version: '3.4'

services:
  pongdb:
    image: mcr.microsoft.com/mssql/server:2022-latest

  pong.api:
    image: ${DOCKER_REGISTRY-}pongapi
    build:
      context: .
      dockerfile: Services/Pong/Pong.API/Dockerfile
