version: '3.4'

services:
  weatherdb:
    image: postgres
    container_name: weatherdb
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
    ports:
      - "5433:5432"